GET http://localhost:8080/status

###

POST http://localhost:8080/videos
Content-Type: application/json

{
  "id": "0da0180c-775a-44db-acfa-534cf5ee2aed",
  "title": "Review de la CommitConf! #CommitCodelyTV",
  "duration_in_seconds": 180,
  "category": "Interview",
  "creator_id": "ba8a348b-71e4-46ec-b11f-7c590537c72b"
}

###
