version: '3'

services:
  mysql:
    container_name: codelytv-cqrs_ddd_scala_example-mysql
    image: mysql/mysql-server:8.0.23
    restart: unless-stopped
    ports:
      - "3316:3306"
    env_file:
      - .env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1
    volumes:
      - ./etc/infrastructure/mysql/init:/docker-entrypoint-initdb.d

  rabbitmq:
    container_name: codelytv-cqrs_ddd_scala_example-rabbitmq
    image: rabbitmq:3.7-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "8181:15672"
    env_file:
      - .env